version: "3"
services:
  server:
    image: uploadbook-back
    ports:
      - 5050:4000
    volumes:
      - ./src:/app/src
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
    # volumes:
    #   - /var/lib/postgresql/data
